USE  riya;
create table EMPLOYEE(EMPLOYEE_ID INT PRIMARY KEY,LAST_NAME VARCHAR(25),JOB_ID VARCHAR(10), SALARY BIGINT ,COMM_PCT DECIMAL(4,2),MGR_ID INT,DEPARTMENT_ID INT);
INSERT INTO EMPLOYEE values(198,'connel','SH_CLERK',2600,2.5,124,50);
INSERT INTO EMPLOYEE values(199,'GRANT','SH_CLERK',2600,2.2,124,50);
INSERT INTO EMPLOYEE values(206,'GITZ','IT_PROG',5000,NULL,103,60);
INSERT INTO EMPLOYEE values(100,'KING','AD_ASST',8956,0.3,108,100);
INSERT INTO EMPLOYEE values(101,'KOCHAR','SH_CLERK',3400,1.3,118,30);
 select EMPLOYEE_ID,LAST_NAME,JOB_ID FROM EMPLOYEE;
 select * from EMPLOYEE where DEPARTMENT_ID =60;
 SELECT  * FROM EMPLOYEE WHERE LAST_NAME ='KING';
 SELECT * FROM EMPLOYEE WHERE COMM_PCT = ' is not  null';
 select EMPLOYEE_ID,DEPARTMENT_ID,SALARY FROM EMPLOYEE WHERE SALARY > '5000';
 SELECT LAST_NAME,SALARY FROM EMPLOYEE WHERE SALARY BETWEEN 4000 AND 7000;
 SELECT * FROM EMPLOYEE where SALARY = 6000 OR SALARY = 6500 OR SALARY = 7000;
 SELECT * FROM EMPLOYEE WHERE DEPARTMENT_ID = 10 OR DEPARTMENT_ID = 20 OR DEPARTMENT_ID = 30 OR DEPARTMENT_ID = 50;
 SELECT * FROM EMPLOYEE WHERE SALARY !=5000;
 SELECT * FROM EMPLOYEE WHERE JOB_ID = 'SH_CLERK';
 SELECT  * FROM EMPLOYEE  WHERE JOB_ID ='SH_CLERK' OR JOB_ID ='IT_PROG' OR JOB_ID ='AD_ASST';
 SELECT * FROM EMPLOYEE WHERE JOB_ID ='SH_CLERK'  AND SALARY < 3000;
 SELECT LAST_NAME,MGR_ID FROM EMPLOYEE  WHERE SALARY > 3000 AND JOB_ID = 'AC_MGR';
  UPDATE  EMPLOYEE SET  JOB_ID = GRADE_A WHERE SALARY > 5000;
  
 